"""
Shared imports for audio

This file contains commonly used imports for audio functionality.
Generated by ImportAnalyzer on 2025-07-14 10:57:28

Usage:
    from pyside_chat.core.shared_imports.audio_imports import *
"""

import pyaudio
import sounddevice as sd
import soundfile as sf
import librosa


# Statistics:
# - Used in 7 files
# - Files: pyside_chat\features\voice\tts\coqui_tts_service.py,
#  pyside_chat\core\shared_imports\audio_imports.py,
# pyside_chat\features\voice\voice_service.py,
#  pyside_chat\features\voice\tts\streaming_audio_player.py,
#  pyside_chat\ui\visualizers\eq_orchestrator.py...
