"""
Shared imports for PySide6 Qt components

This file contains commonly used PySide6 Qt imports for the chat application.
Generated by ImportAnalyzer on 2025-07-14 10:57:28

Usage:
    from pyside_chat.core.shared_imports.pyside_imports import *
    
    # Or import specific components:
    from pyside_chat.core.shared_imports.pyside_imports import QtCore, QtWidgets, QtGui
"""

# =============================================================================
# CORE QT COMPONENTS - MOST COMMONLY USED
# =============================================================================

# QtCore - Core non-GUI functionality
from PySide6.QtCore import (
    # Core objects
    QObject, QThread, QTimer, QEvent, QUrl,

    # Signals and slots
    Signal, Slot, QMetaObject, Q_ARG,

    # Threading and synchronization
    QMutex, QMutexLocker, QWaitCondition, QRunnable, QThreadPool,

    # Application and threading
    Qt, QCoreApplication,

    # Data handling
    QByteArray, QDataStream, QIODevice,

    # Geometry and positioning
    QPoint, QPointF, QRect, QRectF, QSize, QSizeF,

    # Time and date
    QDate, QTime, QDateTime,

    # File system
    QFile, QFileInfo, QDir,

    # Settings
    QSettings,

    # Process management
    QProcess
)

# QtWidgets - GUI widgets and dialogs
from PySide6.QtWidgets import (
    # Main application windows
    QApplication, QMainWindow, QDialog, QWidget,

    # Layout managers
    QVBoxLayout, QHBoxLayout, QGridLayout, QFormLayout, QSplitter,

    # Basic widgets
    QLabel, QPushButton, QLineEdit, QTextEdit, QPlainTextEdit,
    QListWidget, QListWidgetItem, QComboBox, QCheckBox, QRadioButton,
    QSpinBox, QDoubleSpinBox, QSlider, QProgressBar, QScrollArea,
    QTabWidget, QTabBar, QGroupBox, QFrame, QMenu, QMenuBar,
    QStatusBar, QToolBar, QToolButton, QMessageBox, QInputDialog,
    QFileDialog, QColorDialog, QFontDialog,

    # Advanced widgets
    QTableWidget, QTableWidgetItem, QTreeWidget, QTreeWidgetItem,
    QTextBrowser, QCalendarWidget, QDateEdit, QTimeEdit, QDateTimeEdit,
    QSlider, QDial, QLCDNumber, QProgressBar, QScrollBar, QHeaderView,

    # Container widgets
    QStackedWidget, QSplitter, QScrollArea, QMdiArea, QMdiSubWindow,

    # Dialog widgets
    QDialogButtonBox, QWizard, QWizardPage, QProgressDialog,

    # Graphics and visualization
    QGraphicsView, QGraphicsScene, QGraphicsItem, QGraphicsPixmapItem,

    # System integration
    QSystemTrayIcon, QApplication
)

# QtGui - GUI primitives and painting
from PySide6.QtGui import (
    # Painting and drawing
    QPainter, QPainterPath, QPen, QBrush, QColor, QPalette,
    QFont, QFontMetrics, QFontInfo, QTextCursor, QTextCharFormat,

    # Gradients and effects
    QLinearGradient, QRadialGradient, QConicalGradient,

    # Transformations
    QTransform,

    # Images and pixmaps
    QPixmap, QImage, QIcon, QBitmap,

    # Input handling
    QKeyEvent, QMouseEvent, QWheelEvent, QDragEnterEvent, QDropEvent,
    QContextMenuEvent, QFocusEvent, QResizeEvent, QMoveEvent,

    # Text handling
    QTextDocument, QTextBlock, QTextFragment, QTextLayout,

    # Cursor and selection
    QCursor, QDrag,

    # System integration
    QClipboard, QAction, QActionGroup, QShortcut,

    # Accessibility
    QAccessible, QAccessibleInterface
)

# QtMultimedia - Audio and video
from PySide6.QtMultimedia import (
    # Audio playback
    QMediaPlayer, QAudioOutput, QAudioInput, QAudioDevice,

    # Video playback
    # QVideoWidget, QMediaPlaylist,

    # Audio formats
    QAudioFormat, QAudioBuffer, QAudioDecoder,

    # Camera
    QCamera, QCameraDevice, QImageCapture, QMediaRecorder,

    # Sound effects
    QSoundEffect
)

# =============================================================================
# OPTIONAL QT MODULES - IMPORT WITH ERROR HANDLING
# =============================================================================

# QtNetwork - Network functionality (optional)
try:
    from PySide6.QtNetwork import (
        # HTTP and network requests
        QNetworkAccessManager, QNetworkRequest, QNetworkReply,

        # WebSocket support
        QWebSocket, QWebSocketServer,

        # SSL/TLS
        QSslSocket, QSslConfiguration, QSslCertificate,

        # Network information
        QNetworkInterface, QNetworkAddressEntry, QHostAddress,

        # DNS
        QHostInfo, QDnsLookup
    )
    QT_NETWORK_AVAILABLE = True
except ImportError:
    QT_NETWORK_AVAILABLE = False

# QtSql - Database functionality (optional)
try:
    from PySide6.QtSql import (
        # Database connections
        QSqlDatabase, QSqlQuery, QSqlRecord, QSqlField,

        # Database models
        QSqlTableModel, QSqlQueryModel, QSqlRelationalTableModel,

        # Database drivers
        QSqlDriver, QSqlDriverCreator, QSqlDriverCreatorBase
    )
    QT_SQL_AVAILABLE = True
except ImportError:
    QT_SQL_AVAILABLE = False

# QtXml - XML processing (optional)
try:
    from PySide6.QtXml import (
        # XML DOM
        QDomDocument, QDomElement, QDomNode, QDomNodeList,

        # XML parsing
        QXmlStreamReader, QXmlStreamWriter
    )
    QT_XML_AVAILABLE = True
except ImportError:
    QT_XML_AVAILABLE = False

# =============================================================================
# COMMON QT CONSTANTS AND ENUMS
# =============================================================================

# Qt alignment flags
from PySide6.QtCore import (
    Qt,  # Contains all Qt enums
)

# Common Qt enums (from Qt namespace)
Qt_Alignment = Qt.Alignment
Qt_Orientation = Qt.Orientation
Qt_WindowFlags = Qt.WindowFlags
Qt_WindowStates = Qt.WindowStates
Qt_KeyboardModifiers = Qt.KeyboardModifiers
Qt_MouseButtons = Qt.MouseButtons

# =============================================================================
# UTILITY FUNCTIONS FOR QT
# =============================================================================


def is_main_thread() -> bool:
    """Check if current thread is the main (GUI) thread."""
    from PySide6.QtWidgets import QApplication
    from PySide6.QtCore import QThread
    return QThread.currentThread() == QApplication.instance().thread()


def safe_ui_update(func, *args, **kwargs):
    """Safely execute UI update function in the main thread."""
    from PySide6.QtCore import QMetaObject, Q_ARG, Qt
    from PySide6.QtWidgets import QApplication

    if is_main_thread():
        return func(*args, **kwargs)
    else:
        # Use invokeMethod for thread-safe UI updates
        QMetaObject.invokeMethod(
            QApplication.instance(),
            lambda: func(*args, **kwargs),
            Qt.ConnectionType.QueuedConnection
        )


def safe_signal_connect(signal, slot, logger=None):
    """Safely connect a signal to a slot with error handling."""
    try:
        if signal is not None and hasattr(signal, 'connect'):
            signal.connect(slot)
            if logger:
                logger.debug(
                    f"Successfully connected signal {signal} to slot {slot}")
            return True
        else:
            if logger:
                logger.warning(
                    f"Signal {signal} is None or has no connect method")
            return False
    except Exception as e:
        if logger:
            logger.error(
                f"Error connecting signal {signal} to slot {slot}: {e}")
        return False


def safe_signal_disconnect(signal, slot=None, logger=None):
    """Safely disconnect a signal from a slot with error handling."""
    try:
        if signal is not None and hasattr(signal, 'disconnect'):
            if slot is not None:
                signal.disconnect(slot)
            else:
                signal.disconnect()
            if logger:
                logger.debug(f"Successfully disconnected signal {signal}")
            return True
        else:
            if logger:
                logger.warning(
                    f"Signal {signal} is None or has no disconnect method")
            return False
    except Exception as e:
        if logger:
            logger.error(f"Error disconnecting signal {signal}: {e}")
        return False


def create_timer(interval: int = 1000, single_shot: bool = False):
    """Create and configure a QTimer with common settings."""
    timer = QTimer()
    timer.setInterval(interval)
    timer.setSingleShot(single_shot)
    return timer


def create_message_box(title: str, text: str, icon=QMessageBox.Icon.Information,
                       buttons=QMessageBox.StandardButton.Ok):
    """Create a configured message box."""
    msg_box = QMessageBox()
    msg_box.setWindowTitle(title)
    msg_box.setText(text)
    msg_box.setIcon(icon)
    msg_box.setStandardButtons(buttons)
    return msg_box

# =============================================================================
# COMMON QT WIDGET CREATION HELPERS
# =============================================================================


def create_button(text: str, parent=None, enabled: bool = True):
    """Create a configured push button."""
    button = QPushButton(text, parent)
    button.setEnabled(enabled)
    return button


def create_label(text: str, parent=None, alignment=Qt.AlignmentFlag.AlignLeft):
    """Create a configured label."""
    label = QLabel(text, parent)
    label.setAlignment(alignment)
    return label


def create_text_edit(parent=None, placeholder: str = ""):
    """Create a configured text edit widget."""
    text_edit = QTextEdit(parent)
    if placeholder:
        text_edit.setPlaceholderText(placeholder)
    return text_edit


def create_line_edit(parent=None, placeholder: str = ""):
    """Create a configured line edit widget."""
    line_edit = QLineEdit(parent)
    if placeholder:
        line_edit.setPlaceholderText(placeholder)
    return line_edit


def create_combo_box(parent=None, items: list = None):
    """Create a configured combo box widget."""
    combo_box = QComboBox(parent)
    if items:
        combo_box.addItems(items)
    return combo_box


def create_progress_bar(parent=None, minimum: int = 0, maximum: int = 100):
    """Create a configured progress bar."""
    progress_bar = QProgressBar(parent)
    progress_bar.setMinimum(minimum)
    progress_bar.setMaximum(maximum)
    return progress_bar

# =============================================================================
# LAYOUT HELPERS
# =============================================================================


def create_vertical_layout(parent=None, spacing: int = 6, margin: int = 6):
    """Create a configured vertical layout."""
    layout = QVBoxLayout(parent)
    layout.setSpacing(spacing)
    layout.setContentsMargins(margin, margin, margin, margin)
    return layout


def create_horizontal_layout(parent=None, spacing: int = 6, margin: int = 6):
    """Create a configured horizontal layout."""
    layout = QHBoxLayout(parent)
    layout.setSpacing(spacing)
    layout.setContentsMargins(margin, margin, margin, margin)
    return layout


def create_grid_layout(parent=None, spacing: int = 6, margin: int = 6):
    """Create a configured grid layout."""
    layout = QGridLayout(parent)
    layout.setSpacing(spacing)
    layout.setContentsMargins(margin, margin, margin, margin)
    return layout


def create_form_layout(parent=None, spacing: int = 6, margin: int = 6):
    """Create a configured form layout."""
    layout = QFormLayout(parent)
    layout.setSpacing(spacing)
    layout.setContentsMargins(margin, margin, margin, margin)
    return layout

# =============================================================================
# STATISTICS AND USAGE INFO
# =============================================================================

# Statistics:
# - Used in 45+ files across the codebase
# - Most common imports: QTimer, Signal, Qt, QWidget, QVBoxLayout, QHBoxLayout
# - Covers all major Qt modules: Core, Widgets, Gui, Multimedia
# - Optional modules: Network, Sql, Xml (with error handling)
# - Includes utility functions for safe threading and common widget creation

# Common usage patterns:
# - UI components: QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton
# - Threading: QThread, QTimer, Signal, QObject
# - Painting: QPainter, QColor, QPen, QBrush
# - Audio: QMediaPlayer, QAudioOutput
# - Dialogs: QMessageBox, QDialog, QFileDialog
